package com.courseAndStudentManagementSystem.integration;// Generated by Selenium IDE

import org.junit.Test;
import org.openqa.selenium.By;
public class SeleniumStudentTests extends BaseSeleniumTest {

  @Test
  public void createStudent() {
    navigateTo();

    click(By.cssSelector("path"));
    click(By.cssSelector(".MuiListItem-root:nth-child(3) .MuiTypography-root"));

    moveToAndClick(By.cssSelector(".MuiButton-root"));

    typeText(By.id(":r1l:"), "Gabriel Monteiro de Souza");
    typeText(By.id(":r1n:"), "gabriel.monteiro@estudante.sc.senai.br");
    typeText(By.id(":r1p:"), "2000-03-05");

    moveToAndClick(By.id("demo-multiple-name"));
    releaseElement(driver.findElement(By.cssSelector(".MuiBackdrop-root")));

    click(By.cssSelector("body"));
    click(By.cssSelector(".MuiMenuItem-root"));
    click(By.cssSelector(".MuiBackdrop-root"));
    click(By.cssSelector(".MuiButton-root"));
  }

}
